"""baseline schema

Revision ID: f4adf0ae24ea
Revises: 
Create Date: 2026-06-23 12:17:37.436603

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f4adf0ae24ea'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_access_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('forwarded_for', sa.String(length=255), nullable=True, comment='X-Forwarded-For 헤더 값'),
    sa.Column('real_ip', sa.String(length=45), nullable=True, comment='X-Real-IP 헤더 값'),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('os_name', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('browser_name', sa.String(length=50), nullable=True),
    sa.Column('browser_version', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True, comment='desktop, mobile, tablet'),
    sa.Column('device_brand', sa.String(length=50), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(length=2048), nullable=False),
    sa.Column('request_method', sa.String(length=10), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='응답 시간 (밀리초)'),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('accept_language', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_access_logs_browser_name', 'user_access_logs', ['browser_name'], unique=False)
    op.create_index('ix_user_access_logs_country', 'user_access_logs', ['country'], unique=False)
    op.create_index('ix_user_access_logs_created_at', 'user_access_logs', ['created_at'], unique=False)
    op.create_index('ix_user_access_logs_device_type', 'user_access_logs', ['device_type'], unique=False)
    op.create_index('ix_user_access_logs_ip_address', 'user_access_logs', ['ip_address'], unique=False)
    op.create_index('ix_user_access_logs_os_name', 'user_access_logs', ['os_name'], unique=False)
    op.create_index('ix_user_access_logs_session_id', 'user_access_logs', ['session_id'], unique=False)
    op.create_index('ix_user_access_logs_user_id', 'user_access_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # --- 보정 (2026-08-10) -------------------------------------------------
    # 최초 작성 시 user_access_logs 만 담겨 있었고 나머지 도메인 테이블이 통째로
    # 빠져 있었다. 그 결과 다음 리비전(b2f1a9c0d3e4)이 존재하지 않는 users 를
    # ALTER 하면서 빈 DB에서는 upgrade head 자체가 불가능했다. DEBUG 모드의
    # create_db_tables() 가 이 결함을 가려왔다.
    #
    # users 는 hashed_password 없이 만든다 — 그 컬럼 추가는 b2f1a9c0d3e4 의
    # 역할이므로, 여기서 미리 넣으면 후속 리비전이 무의미해진다.
    op.create_table(
        'users',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table(
        'blog_posts',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('author', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'replies',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('author', sa.String(length=100), nullable=True),
        sa.Column('post_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sns_posts',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('author', sa.String(length=100), nullable=True),
        sa.Column('like_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # 보정으로 추가된 테이블 (upgrade 의 역순)
    op.drop_table('sns_posts')
    op.drop_table('replies')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_access_logs_user_id', table_name='user_access_logs')
    op.drop_index('ix_user_access_logs_session_id', table_name='user_access_logs')
    op.drop_index('ix_user_access_logs_os_name', table_name='user_access_logs')
    op.drop_index('ix_user_access_logs_ip_address', table_name='user_access_logs')
    op.drop_index('ix_user_access_logs_device_type', table_name='user_access_logs')
    op.drop_index('ix_user_access_logs_created_at', table_name='user_access_logs')
    op.drop_index('ix_user_access_logs_country', table_name='user_access_logs')
    op.drop_index('ix_user_access_logs_browser_name', table_name='user_access_logs')
    op.drop_table('user_access_logs')
    # ### end Alembic commands ###
